version: '2'
services:
    students-app:
        image: students
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://students-mysql:3306/students?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=students-elasticsearch:9300
        ports:
            - 8080:8080
    students-mysql:
        extends:
            file: mysql.yml
            service: students-mysql
    students-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: students-elasticsearch
